name1=input("Enter your name: ").lower()
print(name1)
name2=input("Enter your name: ").upper()
print(name2)
name3=input("Enter your name: ").capitalize()
print(name3)
name4=input("Enter your name: ").title()
print(name4)
name5=input("Enter your name: ").swapcase()
print(name5)